### ISSUE TITLE
Invalid PIN on trying to upload data

### ISSUE THREAD

**Issue by simonry14** [opentrace-community/opentrace-android#12]
Thanks for the good work.

Whenever I try to upload data I get an invalid pin error message.

I have followed all the cloud functions instructions and the tests all run successfully.

Please kindly advise what I might be missing

**Comment by slxe6** [comment]
Hi simonry14, the getUploadToken requires a pin that is generated on the server. You need to enter this pin in order to upload. Can you double check that you entered the correct pin?

**Comment by rinekri** [comment]
Yeah, you should generate a bunch of pin codes to upload data. You can use **setUploadCodes** function from **getUploadToken.ts file**. But to invoke it you should make some changes to source code, now it's just an unused function.

**Comment by valr2** [comment]
I did manage to get a test pin ('1234') into Firestore, by adding a line at the beginning of getUploadToken() in getUploadToken.ts, that calls "await storeUploadCodes(['1234']);". Afterwards I could see in Cloud Firestore Database a "codes" collection, with an "uploadCode" document.

After doing this, the app still said Invalid Pin, although getUploadToken() executed successfully on the server and returned status: "SUCCESS" and the base64 encoded token to the client. The reason was an exception on the client-side related to SimpleDateFormat('YYYYMMdd') in uploadToCloudStorage() from EnterPinFragment.kt. I've changed the format string to 'yyyyMMdd' and now the whole uploading works, and I see my data inside the upload storage bucket, as unencrypted json.

**Comment by rinekri** [comment]
And I remembered one important thing. I added in the getUploadToken.ts function trimming logic:

`    valid = uploadCodes.find(x => x.trim() === data.trim()) !== undefined;`
It will protect you from insufficient error if you entered spaces accidentally.

**Comment by rez20004** [comment]
@ValentinRadoi can you please share how the code look like that you the added the await storeUploadCodes(['1234']);
thanks in advance.

**Comment by simonry14** [comment]
Thanks all for the feedback. I resolved it by following @ValentinRadoi's advice.

**Comment by esQmo** [comment]
Hey @simonry14 , It will be better if you share your solution with others too

**Comment by Biplovkumar** [comment]
> undefined

Can u plz share @rinekri 
Where it need to be add ?

**Comment by Biplovkumar** [comment]
> Thanks all for the feedback. I resolved it by following @ValentinRadoi's advice.

Can u plz share the solution with class name. @simonry14

**Comment by Hoangtho11188** [comment]
@rinekri I'm facing with the below issue when trying to upload data : 
_Error: 9 FAILED_PRECONDITION: The Cloud Firestore API is not available for Datastore Mode projects._
Could you pls help me on this?

**Comment by Biplovkumar** [comment]
> I did manage to get a test pin ('1234') into Firestore, by adding a line at the beginning of getUploadToken() in getUploadToken.ts, that calls "await storeUploadCodes(['1234']);". Afterwards I could see in Cloud Firestore Database a "codes" collection, with an "uploadCode" document.
> 
> After doing this, the app still said Invalid Pin, although getUploadToken() executed successfully on the server and returned status: "SUCCESS" and the base64 encoded token to the client. The reason was an exception on the client-side related to SimpleDateFormat('YYYYMMdd') in uploadToCloudStorage() from EnterPinFragment.kt. I've changed the format string to 'yyyyMMdd' and now the whole uploading works, and I see my data inside the upload storage bucket, as unencrypted json.

Not helped @valr2.
i hev entered verification code in Enter pin number and changed  'yyyyMMdd' too.
but still facing issue.

**Comment by rinekri** [comment]
@Hoangtho11188 It seems you should change [Firestore Mode to Native](https://cloud.google.com/datastore/docs/firestore-or-datastore).

**Comment by lorsk** [comment]
> I did manage to get a test pin ('1234') into Firestore, by adding a line at the beginning of getUploadToken() in getUploadToken.ts, that calls "await storeUploadCodes(['1234']);". Afterwards I could see in Cloud Firestore Database a "codes" collection, with an "uploadCode" document.
> 
> After doing this, the app still said Invalid Pin, although getUploadToken() executed successfully on the server and returned status: "SUCCESS" and the base64 encoded token to the client. The reason was an exception on the client-side related to SimpleDateFormat('YYYYMMdd') in uploadToCloudStorage() from EnterPinFragment.kt. I've changed the format string to 'yyyyMMdd' and now the whole uploading works, and I see my data inside the upload storage bucket, as unencrypted json.

This has not worked for me. I added the await storeUploadCodes(['1234']); line to see if that helps but its giving me this Invalid key length error: 

![image](https://user-images.githubusercontent.com/17942432/79945627-32003500-843c-11ea-9174-5b50520aa4b6.png)

**Comment by rinekri** [comment]
> 
> 
> > I did manage to get a test pin ('1234') into Firestore, by adding a line at the beginning of getUploadToken() in getUploadToken.ts, that calls "await storeUploadCodes(['1234']);". Afterwards I could see in Cloud Firestore Database a "codes" collection, with an "uploadCode" document.
> 
> > 
> 
> > After doing this, the app still said Invalid Pin, although getUploadToken() executed successfully on the server and returned status: "SUCCESS" and the base64 encoded token to the client. The reason was an exception on the client-side related to SimpleDateFormat('YYYYMMdd') in uploadToCloudStorage() from EnterPinFragment.kt. I've changed the format string to 'yyyyMMdd' and now the whole uploading works, and I see my data inside the upload storage bucket, as unencrypted json.
> 
> 
> 
> This has not worked for me. I added the await storeUploadCodes(['1234']); line to see if that helps but its giving me this Invalid key length error: 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/17942432/79945627-32003500-843c-11ea-9174-5b50520aa4b6.png)
> 
> 

Code should have minimum 6 symbols, try to add 123456 code number.

**Comment by lorsk** [comment]
> Code should have minimum 6 symbols, try to add 123456 code number. 

Hey @rinekri tried that and am getting the same thing unfortunately. What do you think I am missing?

![image](https://user-images.githubusercontent.com/17942432/80006402-d2814400-8492-11ea-9918-6fc4100fccb7.png)

**Comment by lorsk** [comment]
After some investigating, the Invalid key length is coming from the key I generated and uploaded to the [Secret Manager](https://github.com/opentrace-community/opentrace-cloud-functions#encryption-key). I have set it up correctly I believe and it passes all my tests. My default encryption algorithm is "aes-256-gcm".

Not sure where I am going wrong. 

EDIT: 
I was able to successfully upload a key by doing this 
`const key_in_bytes = Buffer.from("FKdDh0d0qUv4FByKxwkZtCPfR87uspUwEokBFRQll5w=", 'base64')`
and passing that instead of `this.key` 

![image](https://user-images.githubusercontent.com/17942432/80011980-9baf2c00-849a-11ea-820c-f85395b6085f.png)
(And similar thing with the same base64 string to the decrypt function)

This means I did something weird with how I generated the key possibly with the `head -c32 /dev/urandom | base64` line

So still not sure what the issue there is.

**Comment by rinekri** [comment]
@LorsK You can add logging of encryption key from SecretManager in the encrypt function. Maybe problem isn't in key itself, but in the way how you added it in the Manager. You could copy key with spaces, new lines and etc.

**Comment by Hoangtho11188** [comment]
@rinekri I getuploadtoken success from my side
![uploadtoken](https://user-images.githubusercontent.com/45715294/80184584-11e79600-8635-11ea-814d-2301dbedb1a3.PNG)
So how to upload data to Storage bucket? My Upload bucket still is empty now.

**Comment by vishaljoseph** [comment]
@LorsK I'm having a similar issue with invalid key length. I'm not quite sure how putting in  'const key_in_bytes = Buffer.from("FKdDh0d0qUv4FByKxwkZtCPfR87uspUwEokBFRQll5w=", 'base64')' would work. What about the key you have stored in the Secret manager?

**Comment by vishaljoseph** [comment]
@Hoangtho11188 I'm having the same issue. Getting this error on checking the logs: E/StorageException: StorageException has occurred.
    User does not have permission to access this object.
     Code: -13021 HttpResult: 403
E/StorageException: The server has terminated the upload session

Were you able to fix it?

**Comment by Bhudipta** [comment]
> Thanks for the good work.
> 
> Whenever I try to upload data I get an invalid pin error message.
> 
> I have followed all the cloud functions instructions and the tests all run successfully.
> 
> Please kindly advise what I might be missing

Hello, can you please tell me how did you initiate file upload? I can not find the option. Thanks.

**Comment by ghost** [comment]
> "await storeUploadCodes(['1234']);"

hello, can you please specify where did you put this "await storeUploadCodes(['1234']);" line? It will be extremely helpful. Thank you.
