### ISSUE TITLE
How to decrypt MSG

### ISSUE THREAD

**Issue by ie76** [opentrace-community/opentrace-android#13]
Hello,

i have an issue decrypting the msg attribute once it's stored. i want to decrypted once i get the records in firestore. 

Thanks

**Comment by rinekri** [comment]
@ie76 did you try a decryptTempID function? I think it should fit for this case, because msgs from firestore should contain temp ids generated by opposite function. I planned to use this approach in the near feature.

**Comment by ie76** [comment]
Well yes i did, but i got a weird string when i used decodeAndDecrypt function. or should i use decodeAndDecrypt and then decryptTempID for msg attribute ?

**Comment by rinekri** [comment]
@ie76 I think, just decryptTempID should be enough, because it's returning json with userId and timestamp. Try to invoke only decryptTempID with msg argument and encryption key obtained from await getEncryptionKey().

**Comment by ie76** [comment]
Thanks a lot for your help. it's worked perfectly ! Thanks again.

**Comment by Hoangtho11188** [comment]
@ie76 can you help me on this?I'm still stuck at here :)

**Comment by ie76** [comment]
> @ie76 can you help me on this?I'm still stuck at here :)

You still cannot decrypt the msg ?

**Comment by Hoangtho11188** [comment]
yes bro, could you pls help me on this?

**Comment by ie76** [comment]
well are you using the nodejs backend too ? if yes there's a little function call decrypt, you can use it to decrypt your string with the private key. Easy

**Comment by Hoangtho11188** [comment]
> well are you using the nodejs backend too ? if yes there's a little function call decrypt, you can use it to decrypt your string with the private key. Easy

Yes, which function? Pls show me the way :)

**Comment by ie76** [comment]
Sure. There's a file called CustomEncrypter.ts with a decryptTempID, you can find more decryptions. you can look there and i'm sure you are going to find a solution
