### ISSUE TITLE
Invalid Pin on upload section

### ISSUE THREAD

**Issue by shedevsn** [opentrace-community/opentrace-android#21]
I get invalid pin when a put the pin for upload. I use storeUploadCodes() to store the pin and i can see in firestore the 
Crypted code but when i enter it in the app it still write invalid pin. I changed the format date to 'yyyyMMdd' under uploadToCloudStorage in EnterPinFragment.kt  but i still get invalid pin.

**Comment by rinekri** [comment]
@shedevsn I got the same error until I added trimming logic https://github.com/opentrace-community/opentrace-android/issues/12#issuecomment-613424603

Maybe it will help you too.

**Comment by shedevsn** [comment]
getUploadToken.kt or getUploadToken.ts i can't find the file (getUploadToken.kt) so i add it in getUploadToken.ts but it doesn't work

**Comment by rinekri** [comment]
@shedevsn then you can add an exception logging in the client upload logic and see what happened. It can help you investigate and fix your problem more efficiently.
