### ISSUE TITLE
In the debug mode every thing work but when i make a release the user register not work

### ISSUE THREAD

**Issue by russellmoya** [opentrace-community/opentrace-android#22]

**Comment by esQmo** [comment]
Have you setup google-services.json for production too? @russellmoya

> Production: ./app/src/release/google-services.json

**Comment by russellmoya** [comment]
yes i find solution , it's sha1 problem

**Comment by russellmoya** [comment]
Another problem . After that an user upload the data , how to retrieve the uid or phone number of the user who upload and uid or phone number of other users who is in upload data of this user .

**Comment by nosecc** [comment]
> Have you setup google-services.json for production too? @russellmoya
> 
> > Production: ./app/src/release/google-services.json
@esQmo do we have to register the app to google play for the release to work as my release not working too?
