### ISSUE TITLE
After that an user upload the data , how to retrieve the uid or phone number of the user who upload and uid or phone number of other users who is in upload data of this user .

### ISSUE THREAD

**Issue by russellmoya** [opentrace-community/opentrace-android#23]

**Comment by esQmo** [comment]
Can you please use a valid title and explain your issue in the "description" section?

**Comment by russellmoya** [comment]
ok

**Comment by russellmoya** [comment]
the user upload data is here : 

{"records":[{"id":1,"modelC":"SM-G935T","modelP":"SM-N975U1","msg":"nwoplaUjOXgskgme4PrQQO7LK3KqETXg7QgQjErpqgWIOOdMF3mQ4t+jHV5CBB5tWXWrsMVXm5hjY1xAmQ\u003d\u003d","org":"SG_OTC","rssi":-65,"timestamp":1587315808,"v":2},{"id":2,"modelC":"SM-G935T","modelP":"SM-N975U1","msg":"nwoplaUjOXgskgme4PrQQO7LK3KqETXg7QgQjErpqgWIOOdMF3mQ4t+jHV5CBB5tWXWrsMVXm5hjY1xAmQ\u003d\u003d","org":"SG_OTC","rssi":-68,"timestamp":1587315991,"v":2},{"id":3,"modelC":"SM-G935T","modelP":"SM-N975U1","msg":"nwoplaUjOXgskgme4PrQQO7LK3KqETXg7QgQjErpqgWIOOdMF3mQ4t+jHV5CBB5tWXWrsMVXm5hjY1xAmQ\u003d\u003d","org":"SG_OTC","rssi":-78,"timestamp":1587315996,"v":2}],"events":[{"id":1,"msg":"Scanning Started","timestamp":1587315753},{"id":2,"msg":"Scanning Stopped","timestamp":1587315761},{"id":3,"msg":"Scanning Started","timestamp":1587315800},{"id":4,"msg":"Scanning Stopped","timestamp":1587315808},{"id":5,"msg":"Scanning Started","timestamp":1587315846},{"id":6,"msg":"Scanning Stopped","timestamp":1587315854},{"id":7,"msg":"Scanning Started","timestamp":1587315894},{"id":8,"msg":"Scanning Stopped","timestamp":1587315902},{"id":9,"msg":"Scanning Started","timestamp":1587315940},{"id":10,"msg":"Scanning Stopped","timestamp":1587315948},{"id":11,"msg":"Scanning Started","timestamp":1587315987},{"id":12,"msg":"Scanning Stopped","timestamp":1587315995}],"token":"ZbQS+oipIXR2v/ydPhdHL2X+v3Ux5YUCgKbUqB0nBtFOZpyiZBrrvNx4Q0cbOy69xeyEjPvle6hBXQqUKk3tFEzH9ubLikeD6Rme22bMOKzyMmOCaEAvxK10BaB/wS+lQONfzWooeOkuoylnk6GiLvpHTA\u003d\u003d"}

**Comment by russellmoya** [comment]
how to know the phone number or the uid of the users in this data uploaded

**Comment by esQmo** [comment]
How did you manage to get the upload PIN? @russellmoya

**Comment by rinekri** [comment]
@russellmoya you can download uploaded file by **ObjectMetadata** and decode **msg** (where contains encoded contacted user id) from the **records** list and **token** (where contains encoded user id who uploaded data). But your token is empty and it seems you are avoided getToken process.

**Comment by russellmoya** [comment]
Thanks a lot @rinekri  for answer me.
i remove the token , but in the original code , i have the token . @rinekri .
i have Encryption secret key , that i store in google cloud secret manager .
but i want know how to decode **msg** and **token**


> @russellmoya you can download uploaded file by **ObjectMetadata** and decode **msg** (where contains encoded contacted user id) from the **records** list and **token** (where contains encoded user id who uploaded data). But your token is empty and it seems you are avoided getToken process.

**Comment by rinekri** [comment]
@russellmoya you can use **decryptTempID** and **validateToken** functions to do this. You can find them in the existing files: [first](https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/getTempIDs.ts) / [second](https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/getUploadToken.ts). For encryptionKey parameter use **await getEncryptionKey()**

**Comment by russellmoya** [comment]
> How did you manage to get the upload PIN? @russellmoya

i modify getUploadToken.ts file . 
in the getUploadToken.ts , i change **if (data)** code .
the new code : 

if (data) {
    //const uploadCodes = await retrieveUploadCodes();
    const uploadCodes = uid.substring(0, 6).toUpperCase();
    console.log('getUploadToken:', `obtained ${uploadCodes.length} upload codes`);
    console.log("voici le code de retrive",uploadCodes);

    if(uploadCodes.length >0){
        if(uploadCodes === data.toUpperCase()){
          valid = true ;
        } else {
            valid = false ;
        }
    }
   // valid = uploadCodes.find(x => x === data) !== undefined;
    console.log('getUploadToken:', `data is ${valid ? 'valid' : 'not valid'} code`);
  }

**Comment by russellmoya** [comment]
> @russellmoya you can use **decryptTempID** and **validateToken** functions to do this. You can find them in the existing files: [first](https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/getTempIDs.ts) / [second](https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/getUploadToken.ts). For encryptionKey parameter use **await getEncryptionKey()**

for msg i use descyptTempID and for token i use validateToken ?  ... @rinekri

**Comment by rinekri** [comment]
@rinekri yeah. This is an example how you can download uploaded data to decrypt it:

```
async function getCurrentUploadedData(event: ObjectMetadata): Promise<UploadedData> {
  return admin.storage().bucket(event.bucket).file(event.name!).download().then(file => {
    const uploadedData = JSON.parse(file[0].toString())
    console.log('getUploadedData:', `Uploaded data token: ${uploadedData.token}`);
    return uploadedData
  }).catch(function (error) {
    console.log("getUploadedData", error);
    return null
  })
}

interface UploadedData {
  records: Record[];
  token: string
}

interface Record {
  id: string,
  msg: string,
  timestamp: string
}
```

**Comment by russellmoya** [comment]
thanks
