### ISSUE TITLE
Gradle sync failed Could not get unknown property 'STORE_URL'

### ISSUE THREAD

**Issue by chorfa007** [opentrace-community/opentrace-android#24]
Hello,

I start building the android application using Android studio and i got the following error :
4/19/20
9:59 PM	Gradle sync started

9:59 PM	Gradle sync failed: Could not get unknown property 'STORE_URL' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=22, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=29, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=41, versionName=1.0.41, applicationId=io.bluetrace.opentrace, testApplicationId=null, testInstrumentationRunner=androidx.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={GITHASH=com.android.builder.internal.ClassFieldImpl@f362edee}, mResValues={build_config_package=com.android.builder.internal.ClassFieldImpl@78503f26}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.Defaul... (show balloon)

It looks like the 2 variables store URL and PRIVACY URL are not correctly configured could you please help?
I'm new in the Android studio if you can share a wiki I could use to generate debug and release versio

**Comment by rinekri** [comment]
@chorfa007 you should create **gradle.properties** file in the project directory and then put there a sample configuration https://github.com/opentrace-community/opentrace-android#configs-in-gradleproperties.

**Comment by ghost** [comment]
@rinekri I think he needs to define the parameters STORE_URL="<Play store URL>"
PRIVACY_URL="<Privacy policy URL>" in properties file. I have the same issue.

**Comment by rinekri** [comment]
> @rinekri I think he needs to define the parameters STORE_URL="<Play store URL>"
> 
> PRIVACY_URL="<Privacy policy URL>" in properties file. I have the same issue. 

Sure, but you should use all parameters, cos they all need to successfully build app, and sample doesn’t contain properties file at all.

**Comment by Biplovkumar** [comment]
[Plz follow this link](https://github.com/opentrace-community/opentrace-android/issues/2)
Add gradle.properties from Configs in gradle.properties [Link](https://github.com/opentrace-community/opentrace-android)

**Comment by itzkou** [comment]
Can I use this project for educational purposes , I am not a government official

**Comment by Jai-GAY** [comment]
@chorfa007 , You create a new Android Studio project then move folders or open the unzip folder as an existing android project or import? What Android Studio version you are using. I use the opening unzip folder as an existing android project plus adding in the [gradle.properties](https://github.com/opentrace-community/opentrace-android#configs-in-gradleproperties), I don't even see the build project button.

**Comment by ikamaru** [comment]
- Create a new file called "gradle.properties" at the root of the project.
- Copy and Past this [Configuration](https://github.com/opentrace-community/opentrace-android#configs-in-gradleproperties)

**Comment by chorfa007** [comment]
Hello, sorry for the late response thanks all for your support
