### ISSUE TITLE
Bluetooth services

### ISSUE THREAD

**Issue by potatoFry** [opentrace-community/opentrace-android#36]
Hey, is it possible to use the bluetooth feature of the application without the cloud functions? Will the Bluetooth feature where one device running open source openTrace and another device running TraceTogether from the playstore be able to communicate and log their encounter?

**Comment by alexissinglaire** [comment]
@potatoFry :  i believe the purpose of the backend is to enable following things:
- phone number registration
- upload bluetooth data
- other security stuff such as exchange tempid, etc

as for scanning between bluetooth device it;s done locally on each device.

if you only need to use mobile function (without cloud), it will need a lot of things you need to change in the mobile app code and for sure the items i listed above surely cannot be handle within local mobile device itself. 

so there is give and take, and without the cloud functions i dont think this app will give descent result that you expect. 

hope it helps.
