### ISSUE TITLE
How to test if its working?

### ISSUE THREAD

**Issue by potatoFry** [opentrace-community/opentrace-android#37]
I have just installed the application on an android phone, how do I test if the application's bluetooth feature is working? Can I test with TraceTogether application found on playstore or must both applications be installed from github.

**Comment by alexissinglaire** [comment]
> I have just installed the application on an android phone, how do I test if the application's bluetooth feature is working? Can I test with TraceTogether application found on playstore or must both applications be installed from github.

@potatoFry : how is the configuration and setup i backend side? is it done and running? as for the app i think you can only use between the debug version (from github)
, not the production version like you have in app store/play store. so you can install both debug version in your 2 devices and tested.

**Comment by potatoFry** [comment]
> > I have just installed the application on an android phone, how do I test if the application's bluetooth feature is working? Can I test with TraceTogether application found on playstore or must both applications be installed from github.
> 
> @potatoFry : how is the configuration and setup i backend side? is it done and running? as for the app i think you can only use between the debug version (from github)
> , not the production version like you have in app store/play store. so you can install both debug version in your 2 devices and tested.

@alexissinglaire sorry for opening multiple issue tickets, would just like to focus on this one. Yes, cloud configurations have been setup, done and running, however 2 devices running the debug version does not seem to communicate with eachother..

**Comment by alexissinglaire** [comment]
@potatoFry : did you manage to display the cards? (tap on the opentrace icon) . btw how you find out the 2 devices not communicating each other?

**Comment by potatoFry** [comment]
![Screenshot_2020-05-06-17-12-29-728_io bluetrace opentrace](https://user-images.githubusercontent.com/57595249/81160817-29236d80-8fbd-11ea-9fdd-fedde5cea6e2.jpg)
This is what i see on both devices, just that UID & SSID is different. Not sure if this is the card though...

**Comment by alexissinglaire** [comment]
@potatoFry : yes, that;s the card i'm referring to. the UID referring to Firebase user uuid (you can check from firebase console under authentication menu). it looks strange that there is no contain in the card at all. 

when you run the app, did you allow the permission for bluetooth? another thing, maybe you need to scan through your logcat in 1 of the device (attached to your computer) and see whether there is any error highlighted.

**Comment by potatoFry** [comment]
when booting openTrace application at the start appear to have 2 errors on boot:
2020-05-06 17:30:32.659 21373-21423/io.bluetrace.opentrace E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/io.bluetrace.opentrace/settings
2020-05-06 17:30:32.664 21373-21429/io.bluetrace.opentrace E/Answers: Failed to retrieve settings
Not sure if this has anything to do with affecting the bluetooth though. And yes, bluetooth permissions have been allowed

**Comment by alexissinglaire** [comment]
@potatoFry : the error you had is only for fabric (analytic tool from firebase and it has been decommissioned). that error also happen to me, but it's not affecting the behavior of the app.

**Comment by potatoFry** [comment]
@alexissinglaire ah yes i thought so too, however that appears to be the only error log highlighted showing up on log cat

**Comment by potatoFry** [comment]
Could you show me your logcat or card to see how it should actually run, might be missing errors that I am not able to find

**Comment by alexissinglaire** [comment]
@potatoFry : did you manage to test the upload function? if yes, check out the data that being uploaded into firebase storage bucket. you can download the data and view it locally. whatever shown in the cards actually also exist in the upload file.

**Comment by potatoFry** [comment]
@alexissinglaire  oh, I have not tried that feature out, will proceed to do so

**Comment by alexissinglaire** [comment]
> Could you show me your logcat or card to see how it should actually run, might be missing errors that I am not able to find

@potatoFry : Hi, this is my screenshot. as for logcat can you email me alexissinglaire@gmail.com and i will reply you with the logcat.

![image](https://user-images.githubusercontent.com/17283778/81168087-ecf60a00-8fc8-11ea-9b1c-83667663488f.png)
