### ISSUE TITLE
Storage Exception while uploading data

### ISSUE THREAD

**Issue by vishaljoseph** [opentrace-community/opentrace-android#38]
I'm getting the following exception inspite of getUploadToken running successfully.

E/StorageException: StorageException has occurred.
    User does not have permission to access this object.
     Code: -13021 HttpResult: 403
E/StorageException: The server has terminated the upload session

What am I missing?

**Comment by alexissinglaire** [comment]
@vishaljoseph : 
did you configure the upload bucket name inside the gradle.properties (STAGING_FIREBASE_UPLOAD_BUCKET)? The name must match with the bucket name you define in firebase storage .

And the rules/permission setup for the bucket must be define similar to the documentation given .

**Comment by vishaljoseph** [comment]
Hi, yes I changed that afterwards but it still doesn't seem to be working. Do I need to reconnect my app with the project or something like that?

**Comment by vishaljoseph** [comment]
It's working now. Thanks! 

A related query was if a 'users' collection is supposed to get created in the database or this is something I should do?
