### ISSUE TITLE
Can not get txPower value

### ISSUE THREAD

**Issue by GianhTran** [opentrace-community/opentrace-android#45]
I tried to get `txPower` in `onScanResult(callbackType: Int, result: ScanResult?)` callback but the value alway is TX_POWER_NOT_PRESENT (127)

May I do anything in wrong way?

**Comment by alexissinglaire** [comment]
@GianhTran : this error might related to your device. can you try another device and see how is the outcome?

**Comment by GianhTran** [comment]
I think so, but I tried some device with android 10, 9 and get the same result, can you guy get the `txPower` ? @alexissinglaire a

**Comment by alexissinglaire** [comment]
@GianhTran : i can get the value so far. the error TX_POWER_NOT_PRESENT (127) you encountered is quite common, especially for android. therefore i cannot say the error is due to this application.
