### ISSUE TITLE
Invalid Code

### ISSUE THREAD

**Issue by supernovahimura** [opentrace-community/opentrace-android#46]
Hi, can you guide me based on this error?

D/UploadFragment: records: []
    status: []
D/UploadFragment:  NOT-IDLE Invalid code

**Comment by alexissinglaire** [comment]
@supernovahimura : have you hardcoded the PIN using the approach below? after you change the code in getUploadToken.ts you need to redeploy the firebase functions. 

await storeUploadCodes(['1234']); inside getUploadToken.ts

**Comment by supernovahimura** [comment]
Thanks @alexissinglaire  now it's working
