### ISSUE TITLE
Task :app:processDebugGoogleServices FAILED

### ISSUE THREAD

**Issue by sudoharish** [opentrace-community/opentrace-android#48]
i have successfully tested 
1)cloud function part, 
2) in sample gradle.properties file as per doc just changed the region to my firebase storage region. 3)created the service.json file from firebase and paste it into the app/debug folder in android studio then synced, 
then i got below  errors, do i need to do anything more, is it mandatory to have android dev account for testing purposes.

```
_> Task :app:processDebugGoogleServices FAILED
Parsing json file: C:\Users\Harish\StudioProjects\opentrace-android\app\src\debug\google-services.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'io.bluetrace.opentrace.stg'_

```

![app_error](https://user-images.githubusercontent.com/53051422/82085534-d8251f00-970a-11ea-9a25-02cd6af48f89.JPG)

**Comment by alexissinglaire** [comment]
@sudoharish: refer to answer for issue #33 for the solution.

**Comment by sudoharish** [comment]
thanks @alexissinglaire
