### ISSUE TITLE
Activity class {io.bluetrace.opentrace.stg/io.bluetrace.opentrace.SplashActivity} does not exist.

### ISSUE THREAD

**Issue by valduze** [opentrace-community/opentrace-android#5]
Hi Guys,
The App fails to startup on AVD, although works fine from my phone except I can't pass the part I pout my number to wait for OTP, it fails with message below: 

```
04/10 20:30:46: Launching 'app' on Pixel 2 API 28.
$ adb shell am start -n "io.bluetrace.opentrace.stg/io.bluetrace.opentrace.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "io.bluetrace.opentrace.stg/io.bluetrace.opentrace.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.bluetrace.opentrace.stg/io.bluetrace.opentrace.SplashActivity }
Error type 3
Error: Activity class {io.bluetrace.opentrace.stg/io.bluetrace.opentrace.SplashActivity} does not exist.

Error while Launching activity
```

I am also failing to register, after putting my phone number, it doesn't go anywhere plus there are no error messages. Am I missing something.
Thanks you,
Jongi

**Comment by valduze** [comment]
This issues disappeared after updating  and sync android

**Comment by rez20004** [comment]
I am also stuck at the level of the  OTP, after i entered the phone number, it does not do anything and have to wait indefinetely. there is something missing at the level of authentications i think!!
