### ISSUE TITLE
f-droid.org repository

### ISSUE THREAD

**Issue by adaschma** [opentrace-community/opentrace-android#55]
It would be great if opentrace would be in the f-droid repository. It similar to google play, but only contains freesoftware (like opentrace is).

**Comment by licaon-kter** [comment]
This app depends on Google Services so this is not really free open-source.

**Comment by adaschma** [comment]
That doesn't mean that it can't be included in the F-Droid store. This is marked with the [Non free Dependencies](https://f-droid.org/wiki/page/Antifeature:NonFreeDep) [anti-feature](https://f-droid.org/wiki/page/AntiFeatures). As of writing [32 Apps](https://f-droid.org/wiki/page/Category:Apps_with_NonFreeDep_antifeature) in the store have this anti-feature.
One nice thing about f-droid is that before installing all anti-features are highlighted so the human can make an informed decision.

**Comment by licaon-kter** [comment]
No, if those app exist they must of been added before 2015, this is no longer the case.

Also, feel free to report them on https://gitlab.com/fdroid/fdroiddata/issues so we can purge them as needed.  

The Wiki is obsolete since Dec 2018, FYI.

**Comment by adaschma** [comment]
I closed this issue as @licaon-kter pointed out, that this isn't possible because the non-free dependency. Thank you @licaon-kter for pointing out my false assumptions.
