### ISSUE TITLE
Wrong OTP entered and OTP expired on debug lofs

### ISSUE THREAD

**Issue by valduze** [opentrace-community/opentrace-android#6]
Hi Guys,
When I try to register the app I get wrong OTP, I am 100% I type it right and when I look at debug logs O get the message below:
```
 com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The sms code has expired. Please re-send the verification code to try again.
        at com.google.firebase.auth.api.internal.zzdv.zza(com.google.firebase:firebase-auth@@19.2.0:30)
```
Can you please assist or I am missing something. 
Thanks,
Jongi

**Comment by slxe6** [comment]
Hi Jongi, Are you still having the issue? The sms code should work. In certain cases you might have to wait a while for the OTP SMS to come in.

**Comment by valduze** [comment]
Hi,
The OTP is still an issue, after  requesting for an OPT, I receive an sms but before I read it, it says verification fail, the when I put the OTP it says wrong OTP, it cannot be wrong I copy and paste from my sms. If I leave my phone for while, or reboot the phone,  and look on notifications I see an app say "Oh no! :( is not scanning." If I click on that, notification my app get activated.

My phone Huawei P20 lite tries to read my sms with OTP code but fails.
I will continue debug.

Please let me know if you find something.
Thanks,
Jongi

**Comment by valduze** [comment]
Hello Guys, 
The issue is verification failure instead of wrong OTP, so I am closing this ticket as the real issue is not OTP wrong but failing to verify.

I will open a ticket for failing to verify, I am closing this one.
Thanks,
Jongi

**Comment by sudoharish** [comment]
I dont know how to implement otp in this app, ehen i build aap it get stuck at register mobile no. On pressing get otp nothing happened. @slxe6 @valduze
