### ISSUE TITLE
opt issue

### ISSUE THREAD

**Issue by rez20004** [opentrace-community/opentrace-android#7]
from the debug screen.. i am getting this message when testing for the OTP
anyone can help please.
D/OnboardingActivity:  NOT-IDLE signInWithCredential:success
D/TempIDManager:  NOT-IDLE [TempID] Error getting Temporary IDs
D/OnboardingActivity:  NOT-IDLE Retrieved Temporary ID successfully
W/Utils:  NOT-IDLE get handshake pin (failure): NOT_FOUND
E/OnboardingActivity:  NOT-IDLE Failed to retrieve HandShakePin NOT_FOUND
I/PhoneAuthProvider: Sms auto retrieval timed-out.

**Comment by slxe6** [comment]
Hi rez20004, you need to setup the corresponding firebase function from opentrace-cloud-functions repo in order to get the getHandShakePin function to work.

**Comment by rez20004** [comment]
> Hi rez20004, you need to setup the corresponding firebase function from opentrace-cloud-functions repo in order to get the getHandShakePin function to work.

Hi slx6
am gettitng this error message although i checked everything is fine:
This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device?

**Comment by rez20004** [comment]
Issue resolved. needed to reconfigured firebase

**Comment by vishaljoseph** [comment]
Hi rez20004, 

I'm having a similar issue inspite of setting up cloud functions and adding the SHA fingerprint. Can you please elaborate on how you solved this?
